### PR TITLE
Add offline access

### PR DESCRIPTION
**Pull request by bennettrogers**
Adds an option to request [offline access](https://developers.google.com/identity/sign-in/web/reference#googleauthgrantofflineaccessoptions).

### CODE REVIEW

**Comment by asyarb** [comment]
Hey @bennettrogers thanks for the PR! I was able to take a quick look and am looking for your thoughts on some proposed changes I've been thinking about. Please feel free to correct me if I'm wrong on any of this as I haven't worked with Google's offline-access before.

**Return a separate function for offline-access**

I think that a separate function that the hook would returns for granting offline access would be a more intuitive API for library users. See below for a rough example:

```jsx
const Component = () => {
  const { grantOfflineAccess } = useGoogleLogin()

  const handleClick = async () => {
    const offlineOptions = {}
    const authCode = await grantOfflineAccess(offlineOptions)

    doStuffWithCode(authCode)
  }

  return (
    <button onClick={handleClick}>Grant offline access</button>
  )
}
```

I think this approach comes with a few benefits:

1. Avoids some user-land confusion that the direct `GoogleAuth` methods and API kind of lend to. The actions of signing in and getting a `authCode` feel like different semantic actions and we can help clarify it at the library level.
2. Keeps the return type of `signIn` as it is now to avoid casting return values as shown below.

```tsx
const googleUser = await signIn() as GoogleUser
```

Let me know what you think!

**Comment by asyarb** [comment]
I've created a branch and PR with the above revisions in mind in #14.

**Comment by bennettrogers** [comment]
#14 Looks excellent! Your approach makes way more sense than mine.

Thank you for looking at this so quickly!

**Comment by asyarb** [comment]
Closing this in favor of #14 which has been merged and released as `0.12.0`.

**Pull request closed without merging**
